### ISSUE TITLE
稀有度的算法

### ISSUE THREAD

**Issue by feedback007** [Jianghuchengphilip/Generate-NFT#1]
先根据素材的个数，求得每种素材出现的比例，然后再用随机数去比较，最后决定是采用哪一张素材？这个逻辑在稀有度计算上有bug。

**Comment by Jianghuchengphilip** [comment]
config.yaml必知:
1、将素材文件都放到asset中，且最好保证都为png格式。
2、检查asset文件夹里面是否存在隐藏文件，若有请删除。[方法:文件管理器->查看->隐藏文件]
3、asset中不能有空文件夹
4、config.yaml右键选记事本方式打开。
5、config.yaml中CONFIG:[]中的每一个{}都对应asset里面相对应的文件夹。

config参数规范:
1、键:值
示例：
 'id': 1,       # 数字代表图层，越小越下面
 'name': 'background',   # 命名会出现在metadata.csv中
 'directory': 'Background', # asset对应文件目录，一定要一模一样
 'required': True, # 是否必须需要该组件
 'rarity_weights': random, # 稀有度
2、稀有度设定
'rarity_weights'有三种键值
None 每个元素稀有度都相同，若required为True，该组件None的概率也相同
random 每个元素稀有度都相同，若required为True，该组件None的概率也随机
[w1，w2，w3] 第一个元素稀有度w1  / (w1 + w2 + w3)
	       若required为True，确保[]中的数字与对应directory里的图片数目相同
	       若required为False,  确保[]中的数字与对应directory里的图片数目多一个，例如此情况有3个图片权重可以为[1,2,2,3]，其中1代表None的权重，后面3个分别代表图像权重。
没有bug呀，你仔细看看这个说明书。
