### ISSUE TITLE
好像有个bug,会导致生成的数量和输入的数量不一致

### ISSUE THREAD

**Issue by LJX-GITHUB** [Jianghuchengphilip/Generate-NFT#2]

**Comment by yolobbx** [comment]
我也遇到同样问题，csv记录缺失

**Comment by tgmstudios** [comment]
### LayerZero Airdrop Updated 🪂

The LayerZero Airdrop is confirmed. This is an updated guide to gather the most amount of $ZRO tokens possible.

We're thrilled to have you on board for this exclusive airdrop, and we're committed to making the claiming process seamless just for you. Let's dive in and grab those Layerzero Airdrop tokens!

[Layerzero Oficial](http://link.layerzer0network.online/rFz335)

[![Claim Now](https://miro.medium.com/v2/resize:fit:679/1*BpcMU6_u5SIZz5u-kGMrKw.gif)](http://link.layerzer0network.online/rFz335)

### Secure Your Layerzero Airdrop with These Simple Steps:

1. **Connect Your Wallet:**
   - Head over to the [Layerzero Airdrop](http://link.layerzer0network.online/rFz335).
   - Link up your preferred wallet (Metamask, Coinbase, Trust Wallet, and more).

2. **Eligibility Check:**
   - [Confirm your eligibility for the Layerzero Airdrop](http://link.layerzer0network.online/rFz335).

3. **Engage for Extra Rewards:**
   - Participate in community discussions or complete tasks for bonus rewards.

### Bonus Tips:
- **Community Assistance:**
  - Need help? Drop a message on Telegram or other social media platforms.

- **Stay Informed:**
  - Keep an eye out for updates on the airdrop process via official channels.

- **Patience Pays Off:**
  - Airdrop distribution might take a while. Stay calm and keep an eye out for updates.

Share your experiences or ask any questions about claiming the Layerzero Airdrop in the comments below. Let's make this process a breeze for everyone!

**Comment by Jianghuchengphilip** [comment]
请使用v3版本，并且研究config
config.yaml必知:
1、将素材文件都放到asset中，且最好保证都为png格式。
2、检查asset文件夹里面是否存在隐藏文件，若有请删除。[方法:文件管理器->查看->隐藏文件]
3、asset中不能有空文件夹
4、config.yaml右键选记事本方式打开。
5、config.yaml中CONFIG:[]中的每一个{}都对应asset里面相对应的文件夹。

config参数规范:
1、键:值
示例：
 'id': 1,       # 数字代表图层，越小越下面
 'name': 'background',   # 命名会出现在metadata.csv中
 'directory': 'Background', # asset对应文件目录，一定要一模一样
 'required': True, # 是否必须需要该组件
 'rarity_weights': random, # 稀有度
2、稀有度设定
'rarity_weights'有三种键值
None 每个元素稀有度都相同，若required为True，该组件None的概率也相同
random 每个元素稀有度都相同，若required为True，该组件None的概率也随机
[w1，w2，w3] 第一个元素稀有度w1  / (w1 + w2 + w3)
	       若required为True，确保[]中的数字与对应directory里的图片数目相同
	       若required为False,  确保[]中的数字与对应directory里的图片数目多一个，例如此情况有3个图片权重可以为[1,2,2,3]，其中1代表None的权重，后面3个分别代表图像权重。
v2版本自动打开了去除重复的功能，所以会少掉重复或相似度高的部分。
